version: "3.3"

services:
  client:
    build: ./packages/client
    container_name: tafd_client
    command: yarn start
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - api
    #    env_file:
    #      - ./api/.env
    networks:
      - tafd_network

  api:
    build: ./packages/server
    container_name: tafd_server
    command: yarn start
    restart: unless-stopped
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    #    env_file:
    #      - ./api/.env
    networks:
      - tafd_network

  mongodb:
    image: mongo
    container_name: mongodb_tafd
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - mongodb-data:/data/dbConfig
    networks:
      - tafd_network
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express_tafd
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - mongodb-data
    depends_on:
      - mongodb
    networks:
      - tafd_network
    ports:
      - 8081:8081
    restart: unless-stopped

volumes:
  mongodb-data:

networks:
  tafd_network:
    driver: bridge